# Generated by Django 3.0.4 on 2020-04-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyreg',
            name='current_auction_status',
        ),
        migrations.RemoveField(
            model_name='propertyreg',
            name='scheduled_status',
        ),
        migrations.AddField(
            model_name='currentauction',
            name='current_auction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentauction',
            name='scheduled_status',
            field=models.BooleanField(default=False),
        ),
    ]
