# Generated by Django 3.0.4 on 2020-03-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentuser',
            options={'verbose_name': 'AgentUser', 'verbose_name_plural': 'AgentUsers'},
        ),
        migrations.AlterField(
            model_name='agentuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agentuser',
            name='interview_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentuser',
            name='interviewed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='agentuser',
            name='proof_document',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agentuser',
            name='resume_document',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='To be Setup', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='To be Setup', max_length=13),
        ),
    ]
