# Generated by Django 3.0.4 on 2020-03-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreg',
            name='city',
            field=models.CharField(default='Place to be Selected.', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyreg',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='propertyreg',
            name='state',
            field=models.CharField(default='To be Selected', max_length=30),
        ),
    ]
