# Generated by Django 3.0.4 on 2020-04-08 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeanoffer',
            name='offer_amount',
        ),
        migrations.RemoveField(
            model_name='propertyreg',
            name='current_auction_status',
        ),
        migrations.RemoveField(
            model_name='propertyreg',
            name='scheduled_status',
        ),
        migrations.AddField(
            model_name='currentauction',
            name='current_auction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentauction',
            name='highest_bidder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.User'),
        ),
        migrations.AddField(
            model_name='currentauction',
            name='next_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currentauction',
            name='scheduled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='makeanoffer',
            name='enquiry',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='makeanoffer',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=13),
        ),
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 15, 30, 1, 929261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='increment_ratio',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='regforauction',
            name='payment_status',
            field=models.CharField(default='Not Paid', max_length=12),
        ),
    ]
