# Generated by Django 3.0.4 on 2020-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentauction',
            name='current_ending_time',
            field=models.DateTimeField(null=True),
        ),
    ]
