# Generated by Django 3.0.4 on 2020-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200321_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(blank=True, default='000000', max_length=6),
        ),
    ]
