# Generated by Django 3.0.4 on 2020-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200411_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='user_bid_amount',
            field=models.IntegerField(null=True),
        ),
    ]
