# Generated by Django 3.0.4 on 2020-04-10 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200410_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 13, 10, 41, 649588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='regforauction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to='auctions.User'),
        ),
    ]
