# Generated by Django 3.0.4 on 2020-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200326_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuser',
            name='user_type',
            field=models.CharField(default='agent', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
