# Generated by Django 3.0.4 on 2020-04-20 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200420_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentauction',
            name='auction_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 12, 44, 25, 230941, tzinfo=utc), null=True),
        ),
    ]
