# Generated by Django 3.0.4 on 2020-04-08 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200408_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 15, 57, 56, 442728, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='propertyreg',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
