# Generated by Django 3.0.4 on 2020-04-08 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200408_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 35, 22, 73995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='regforauction',
            name='payment_status',
            field=models.CharField(default='Not Paid', max_length=12),
        ),
    ]
