# Generated by Django 3.0.4 on 2020-03-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200329_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='currentauction',
            name='current_auction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentauction',
            name='scheduled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentauction',
            name='viewinghours',
            field=models.CharField(default='None2', max_length=20),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.State')),
            ],
        ),
    ]
