# Generated by Django 3.0.4 on 2020-04-08 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200408_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 15, 59, 34, 164819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='propertyreg',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_approves', to='auctions.AgentUser'),
        ),
    ]
