# Generated by Django 3.0.4 on 2020-04-21 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200420_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='regforauction',
            name='invoice_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='auction_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 8, 34, 57, 704278, tzinfo=utc), null=True),
        ),
    ]
