# Generated by Django 3.0.4 on 2020-03-30 11:33

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200329_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFilesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to=auctions.models.generate_filename)),
                ('property_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_files', to='auctions.PropertyReg')),
            ],
        ),
    ]
