# Generated by Django 3.0.4 on 2020-04-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200405_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentauction',
            name='image_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.PropertyImagesUpload'),
        ),
    ]
