# Generated by Django 3.0.4 on 2020-03-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200330_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.City'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.State'),
        ),
    ]
