# Generated by Django 3.0.4 on 2020-03-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200331_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreg',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
