# Generated by Django 3.0.4 on 2020-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_user_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default='000000'),
        ),
    ]
