# Generated by Django 3.0.4 on 2020-04-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200405_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentauction',
            name='image_id',
        ),
    ]
