# Generated by Django 3.0.4 on 2020-03-30 12:05

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_propertyfilesupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImagesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=auctions.models.generate_image_name)),
                ('property_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='auctions.PropertyReg')),
            ],
        ),
    ]
