# Generated by Django 3.0.4 on 2020-04-08 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200408_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentuser',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 16, 3, 37, 249560, tzinfo=utc)),
        ),
    ]
