# Generated by Django 3.0.4 on 2020-04-08 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200408_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 16, 11, 47, 664278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='registration_fees',
            field=models.IntegerField(default=0),
        ),
    ]
