# Generated by Django 3.0.4 on 2020-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_propertyimagesupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreg',
            name='property_description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
