# Generated by Django 3.0.4 on 2020-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200330_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentauction',
            name='current_auction_status',
        ),
        migrations.RemoveField(
            model_name='currentauction',
            name='pre_set_amount',
        ),
        migrations.RemoveField(
            model_name='currentauction',
            name='scheduled_status',
        ),
        migrations.RemoveField(
            model_name='currentauction',
            name='viewinghours',
        ),
        migrations.AddField(
            model_name='propertyreg',
            name='current_auction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyreg',
            name='pre_set_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyreg',
            name='scheduled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyreg',
            name='viewinghours',
            field=models.CharField(default='None2', max_length=20),
        ),
    ]
