# Generated by Django 3.0.4 on 2020-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_currentauction_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeanoffer',
            name='offer_amount',
        ),
        migrations.AddField(
            model_name='currentauction',
            name='next_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='makeanoffer',
            name='enquiry',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='makeanoffer',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=13),
        ),
    ]
