# Generated by Django 3.0.4 on 2020-03-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='To be Setup', max_length=255)),
                ('mobile', models.CharField(default='To be Setup', max_length=13)),
                ('birth_date', models.DateField(blank=True)),
                ('pincode', models.IntegerField(default='000000')),
                ('city', models.CharField(default='Place to be Selected.', max_length=30)),
                ('state', models.CharField(default='To be Selected', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('profile_setup', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='auctions.User')),
            ],
        ),
    ]
