# Generated by Django 3.0.4 on 2020-03-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200325_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_setup',
        ),
    ]
