# Generated by Django 3.0.4 on 2020-04-07 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200407_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentauction',
            name='highest_bidder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.User'),
        ),
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 18, 24, 52, 598222, tzinfo=utc)),
        ),
    ]
