# Generated by Django 3.0.4 on 2020-04-08 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200408_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 16, 16, 10, 49898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='highest_bidder',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.User'),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='auctions.PropertyReg'),
        ),
    ]
