# Generated by Django 3.0.4 on 2020-04-08 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200408_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 16, 57, 39, 110944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='auctions.PropertyReg'),
        ),
    ]
