# Generated by Django 3.0.4 on 2020-03-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200326_1217'),
        ('auctions', '0002_auto_20200321_1547'),
    ]

    operations = [
    ]
