# Generated by Django 3.0.4 on 2020-04-09 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200409_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentauction',
            old_name='property_reg',
            new_name='property_id',
        ),
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 5, 12, 23, 376833, tzinfo=utc)),
        ),
    ]
