# Generated by Django 3.0.4 on 2020-04-09 05:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200409_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 5, 23, 9, 225487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currentauction',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property', to='auctions.PropertyReg'),
        ),
    ]
