# Generated by Django 3.0.4 on 2020-04-09 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200409_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentauction',
            name='highest_bidder',
        ),
        migrations.RemoveField(
            model_name='currentauction',
            name='next_bid',
        ),
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 5, 52, 19, 413214, tzinfo=utc)),
        ),
    ]
