# Generated by Django 3.0.4 on 2020-04-09 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200409_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentauction',
            name='next_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biddingofproperty',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 5, 58, 25, 733909, tzinfo=utc)),
        ),
    ]
